### ISSUE TITLE
Why does the 4090 with 16GB of video memory always prompt that it's running out of memory?

### ISSUE THREAD

**Issue by bayun2016** [kijai/ComfyUI-PyramidFlowWrapper#24]
I am using an RTX 4090 Laptop GPU with 16GB of video memory, and the text-to-video workflow in the instance keeps running out of memory, no matter how I adjust the parameters, the situation is the same.

Total VRAM 16376 MB, total RAM 65225 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post1
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
Using xformers cross attention
............................................................................
got prompt
Using temporal causal attention
We interp the position embedding of condition latents
The latent dimmension channes is 16
The start sigmas and end sigmas of each stage is Start: {0: 1.0, 1: 0.8002399489209289, 2: 0.5007496155411024}, End: {0: 0.6669999957084656, 1: 0.33399999141693115, 2: 0.0}, Ori_start: {0: 1.0, 1: 0.6669999957084656, 2: 0.33399999141693115}
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "E:\develop-tools\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\develop-tools\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\develop-tools\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\develop-tools\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 199, in sample
    latents = model["model"].generate(
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 623, in generate
    intermed_latents = self.generate_one_unit(
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 254, in generate_one_unit
    noise_pred = self.dit(
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\modeling_pyramid_mmdit.py", line 423, in forward
    encoder_hidden_states, hidden_states = block(
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\modeling_mmdit_block.py", line 641, in forward
    attn_output, context_attn_output = self.attn(
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\modeling_mmdit_block.py", line 514, in forward
    query = self.norm_q(query)
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\develop-tools\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\modeling_normalization.py", line 56, in forward
    variance = hidden_states.to(torch.float32).pow(2).mean(-1, keepdim=True)
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 31.26 seconds

**Comment by kijai** [comment]
I have no idea, you didn't change anything in the workflow? Just launched Comfy to see if anything has changed, loaded the default and queued, doesn't even use 10GB for me: 

![image](https://github.com/user-attachments/assets/68544fa6-bb42-44e8-b3f6-b3929f2e3b58)
