### ISSUE TITLE
cannot access local variable 'params_to_keep' with fp8_e4m3fn_fast

### ISSUE THREAD

**Issue by Ratinod** [kijai/ComfyUI-PyramidFlowWrapper#47]
```
!!! Exception during processing !!! cannot access local variable 'params_to_keep' where it is not associated with a value
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 197, in loadmodel
    convert_fp8_linear(transformer, torch.bfloat16, params_to_keep=params_to_keep)
                                                                   ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'params_to_keep' where it is not associated with a value
```

**Comment by kijai** [comment]
Should be fixed now.
